// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0LZtJBfiwAwQEbeGWOSzKaC2iZ_6ErR8',
    appId: '1:467017705192:web:86d20f2d78d960645a4b5d',
    messagingSenderId: '467017705192',
    projectId: 'algorithm-avengers-3008d',
    authDomain: 'algorithm-avengers-3008d.firebaseapp.com',
    storageBucket: 'algorithm-avengers-3008d.appspot.com',
    measurementId: 'G-YMLSFCYDP5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxjkCTWz7UKnyf_4UIeEn8zegBM-X0_2A',
    appId: '1:467017705192:android:86929f00a7ce121e5a4b5d',
    messagingSenderId: '467017705192',
    projectId: 'algorithm-avengers-3008d',
    storageBucket: 'algorithm-avengers-3008d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1uxvC9004ys3GWHJiNnJNdJdnhOiVK-k',
    appId: '1:467017705192:ios:e784c341424e9dde5a4b5d',
    messagingSenderId: '467017705192',
    projectId: 'algorithm-avengers-3008d',
    storageBucket: 'algorithm-avengers-3008d.appspot.com',
    iosBundleId: 'com.example.signupRestLogin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB1uxvC9004ys3GWHJiNnJNdJdnhOiVK-k',
    appId: '1:467017705192:ios:bd0eb77555a7ee4b5a4b5d',
    messagingSenderId: '467017705192',
    projectId: 'algorithm-avengers-3008d',
    storageBucket: 'algorithm-avengers-3008d.appspot.com',
    iosBundleId: 'com.example.signupRestLogin.RunnerTests',
  );
}
